OCAMLC   = ocamlfind ocamlc
OCAMLOPT = ocamlfind ocamlopt

include ../../../config

DOTVIEW=open -a Graphviz

all: run

run: a.out
	./a.out

a.out: $(SRCS)
	$(OCAMLC) -I ../../../src/utils -I ../../../src/lib utils.cma lascar.cma $<

clean:
	@\rm -f a.out *.cmi *.cmo
	@\rm -f *.dot *.tex
	@\rm -f *~
